Only start vm if it is in a powered-off state. Otherwise, just connect.

diff --git a/vbox-start-vm/vbox-start-vm b/vbox-start-vm/vbox-start-vm
--- a/vbox-start-vm/vbox-start-vm
+++ b/vbox-start-vm/vbox-start-vm
@@ -3,18 +3,42 @@
 
 vm_name="$@"
 
-if [ -z "$vm_name" ] ; then
-	echo "Must specify vm on command line." >&2
+function die () {
+	local msg="$1"
+	echo "ERROR: ${msg}" >&2
 	exit 1
-fi
+}
 
-VBoxManage startvm "$vm_name" --type headless
-if [ "$?" -ne 0 ] ; then
-	echo
-	echo
-	echo "Could not start the vm, exiting..."
-	exit 1
-fi
+function start_vm () {
+	local vm_name="$1"
+
+	echo "Starting \"${vm_name}\""
+	VBoxManage startvm "$vm_name" --type headless
+	if [ "$?" -ne 0 ] ; then
+		echo
+		echo
+		die "Could not start the vm, exiting..."
+	fi
+}
+
+[ -z "$vm_name" ] && die "Must specify vm on command line."
+
+# find state of vm
+vm_state="$(VBoxManage showvminfo "$vm_name" | grep "^State:" | sed -e 's/State:\s\+\([A-Za-z ]\+\).*$/\1/ ; s/\s\+$//')"
+
+# start vm if it is not already running
+case "$vm_state" in
+	powered\ off|saved)
+		start_vm "${vm_name}"
+		;;
+	running)
+		# do nothing
+		:
+		;;
+	*)
+		die "When looking at \"${vm_name}\", found unknown state: ${vm_state}"
+		;;
+esac
 
 echo -n "Trying to connect..."
 while ((1)) ; do
